# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/joe/Downloads/clion-2016.2.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/joe/Downloads/clion-2016.2.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joe/dev/CommandLineScrabble

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joe/dev/CommandLineScrabble/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/joe/Downloads/clion-2016.2.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/joe/Downloads/clion-2016.2.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joe/dev/CommandLineScrabble/cmake-build-debug/CMakeFiles /home/joe/dev/CommandLineScrabble/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joe/dev/CommandLineScrabble/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CommandLineScrabble

# Build rule for target.
CommandLineScrabble: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CommandLineScrabble
.PHONY : CommandLineScrabble

# fast build rule for target.
CommandLineScrabble/fast:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/build
.PHONY : CommandLineScrabble/fast

letterBag.o: letterBag.cpp.o

.PHONY : letterBag.o

# target to build an object file
letterBag.cpp.o:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/letterBag.cpp.o
.PHONY : letterBag.cpp.o

letterBag.i: letterBag.cpp.i

.PHONY : letterBag.i

# target to preprocess a source file
letterBag.cpp.i:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/letterBag.cpp.i
.PHONY : letterBag.cpp.i

letterBag.s: letterBag.cpp.s

.PHONY : letterBag.s

# target to generate assembly for a file
letterBag.cpp.s:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/letterBag.cpp.s
.PHONY : letterBag.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/main.cpp.s
.PHONY : main.cpp.s

player.o: player.cpp.o

.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i

.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s

.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/player.cpp.s
.PHONY : player.cpp.s

playerTileSet.o: playerTileSet.cpp.o

.PHONY : playerTileSet.o

# target to build an object file
playerTileSet.cpp.o:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/playerTileSet.cpp.o
.PHONY : playerTileSet.cpp.o

playerTileSet.i: playerTileSet.cpp.i

.PHONY : playerTileSet.i

# target to preprocess a source file
playerTileSet.cpp.i:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/playerTileSet.cpp.i
.PHONY : playerTileSet.cpp.i

playerTileSet.s: playerTileSet.cpp.s

.PHONY : playerTileSet.s

# target to generate assembly for a file
playerTileSet.cpp.s:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/playerTileSet.cpp.s
.PHONY : playerTileSet.cpp.s

tile.o: tile.cpp.o

.PHONY : tile.o

# target to build an object file
tile.cpp.o:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/tile.cpp.o
.PHONY : tile.cpp.o

tile.i: tile.cpp.i

.PHONY : tile.i

# target to preprocess a source file
tile.cpp.i:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/tile.cpp.i
.PHONY : tile.cpp.i

tile.s: tile.cpp.s

.PHONY : tile.s

# target to generate assembly for a file
tile.cpp.s:
	$(MAKE) -f CMakeFiles/CommandLineScrabble.dir/build.make CMakeFiles/CommandLineScrabble.dir/tile.cpp.s
.PHONY : tile.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CommandLineScrabble"
	@echo "... letterBag.o"
	@echo "... letterBag.i"
	@echo "... letterBag.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... playerTileSet.o"
	@echo "... playerTileSet.i"
	@echo "... playerTileSet.s"
	@echo "... tile.o"
	@echo "... tile.i"
	@echo "... tile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

